
services:
  app:
    image: progresssoft-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/progressSoft
      - SPRING_DATASOURCE_USERNAME=asmaa
      - SERVER_PORT=8085

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=progressSoft
      - POSTGRES_USER=asmaa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: